### ISSUE TITLE
flake8 maximum recursion depth exceeded

### ISSUE THREAD

**Issue by lukemarsden** [samalba/hf-model-ops#3]
Strange error, can't figure out why this is happening...

On this commit: https://github.com/lukemarsden/hf-model-ops/tree/ba2f2411bca5dab481b580400051818c67158486

```
(.venv) luke@floating:~/pd/hf-model-ops$ python ./ci/lint.py
/home/luke/pd/hf-model-ops/./ci/lint.py:36: DeprecationWarning: The synchronous API is deprecated and will be removed in a future release. See https://github.com/dagger/dagger/issues/5192 for more information.
  with dagger.Connection(dagger.Config(log_output=sys.stderr)) as client:
Connected to engine 5a84bd754533
#1 resolve image config for docker.io/library/python:3.11-slim-buster
#1 DONE 0.7s

#2 lint
#2 DONE 0.0s

#3 from python:3.11-slim-buster
#3 resolve docker.io/library/python:3.11-slim-buster@sha256:9861d22af8ed68875e59a4187c0b99aa03e01aaf82f565e9548ec3c3fc2a325e 0.0s done
#3 DONE 0.0s

#4 host.directory /home/luke/pd/hf-model-ops/src
#4 transferring /home/luke/pd/hf-model-ops/src: 479.88kB 0.1s
#4 transferring /home/luke/pd/hf-model-ops/src: 3.74MB 0.9s done
#4 DONE 0.9s

#4 host.directory /home/luke/pd/hf-model-ops/src
#4 DONE 0.9s

#2 lint


#2 84.63 ./.venv/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: "pyflakes[F]" failed during execution due to RecursionError('maximum recursion depth exceeded')
#2 84.63 Run flake8 with greater verbosity to see more details
#2 ERROR: process "flake8" did not complete successfully: exit code: 1
------
 > lint:
84.63 ./.venv/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: "pyflakes[F]" failed during execution due to RecursionError('maximum recursion depth exceeded')
84.63 Run flake8 with greater verbosity to see more details
------
Traceback (most recent call last):
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/dagger/api/base.py", line 170, in _handle_execute
    yield
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/dagger/api/base.py", line 123, in execute_sync
    result = self.session.execute(query)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/gql/client.py", line 860, in execute
    raise TransportQueryError(
gql.transport.exceptions.TransportQueryError: {'message': 'process "flake8" did not complete successfully: exit code: 1', 'locations': [{'line': 14, 'column': 21}], 'path': ['pipeline', 'container', 'from', 'withDirectory', 'withWorkdir', 'withMountedCache', 'withEnvVariable', 'withExec', 'withExec', 'exitCode'], 'extensions': {'_type': 'EXEC_ERROR', 'cmd': ['flake8'], 'exitCode': 1, 'stderr': '', 'stdout': './.venv/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: "pyflakes[F]" failed during execution due to RecursionError(\'maximum recursion depth exceeded\')\nRun flake8 with greater verbosity to see more details'}}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/luke/pd/hf-model-ops/./ci/lint.py", line 37, in <module>
    lint(client)
  File "/home/luke/pd/hf-model-ops/./ci/lint.py", line 31, in lint
    python.exit_code()
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/dagger/api/base.py", line 366, in wrapper
    return bear(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(dagger.api.gen_sync.Container.exit_code) at 0x7f28ef8353a0>", line 10, in exit_code
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/dagger/api/gen_sync.py", line 385, in exit_code
    return _ctx.execute_sync(int)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/dagger/api/base.py", line 122, in execute_sync
    with self._handle_execute(query):
  File "/usr/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/luke/pd/hf-model-ops/ci/.venv/lib/python3.11/site-packages/dagger/api/base.py", line 196, in _handle_execute
    raise error from e
dagger.exceptions.ExecError: process "flake8" did not complete successfully: exit code: 1
Stdout:
./.venv/lib/python3.11/site-packages/sympy/polys/numberfields/resolvent_lookup.py: "pyflakes[F]" failed during execution due to RecursionError('maximum recursion depth exceeded')
Run flake8 with greater verbosity to see more details
Stderr:
```

**Comment by samalba** [comment]
Do you have this one constantly? I never hit it. Do you have uncommitted files in your src/ dir that might trigger that error?

**Comment by lukemarsden** [comment]
I don't think so, but I'll try again from a fresh checkout
